import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ethnocentric = localFont({
  src: [{ path: "../fonts/ethnocentric rg.otf", weight: "400" }],
  variable: "--font-ethnocentric"
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${ethnocentric.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
